---
language: python
python: "2.7"

dist: trusty
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\npipelining=true\nhost_key_checking=false' >ansible.cfg

script:
  - eval "ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -b 1024 -N ''"
  - eval "cp $HOME/.ssh/id_rsa $HOME/.ssh/authorized_keys"
  - eval "ssh-keygen -f \"$HOME/.ssh/known_hosts\" -R localhost"
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Actual tests
  - eval "ansible-playbook -vvvvvv tests/test.yml -i tests/inventory --user $USER --connection=local"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
